### ISSUE TITLE
fail build with latest sdk (2.1.1)

### ISSUE THREAD

**Issue by sl1pkn07** [X360Tools/PicoFlasher#56]
```make
[ 15%] Building C object CMakeFiles/PicoFlasher.dir/main.c.o
/home/sl1pkn07/aplicaciones/Microsoft XBOX 360/PicoFlasher/main.c:21:10: fatal error: bsp/board.h: No such file or directory
   21 | #include "bsp/board.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/PicoFlasher.dir/build.make:79: CMakeFiles/PicoFlasher.dir/main.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2261: CMakeFiles/PicoFlasher.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

fixed with

```patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 5391bfc..05e1742 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -37,6 +37,7 @@ pico_generate_pio_header(${PROJECT_NAME} ${CMAKE_CURRENT_LIST_DIR}/sdio.pio)
 # Link to pico_stdlib (gpio, time, etc. functions)
 target_link_libraries(${PROJECT_NAME} 
     pico_stdlib
+       tinyusb_board
        tinyusb_device_unmarked
        hardware_pio
        hardware_spi
```

over linux

**Comment by prodeveloper0** [comment]
https://github.com/prodeveloper0/PicoFlasher/blob/master/BUILD.md
